[package]
edition = "2021"
name = "web-sys"
rust-version = "1.59"
version = "0.0.0"

[build-dependencies]
js-bindgen-bootstrap = { path = "../bootstrap" }

[dependencies]
js-bindgen = { path = "../js-bindgen" }
js-sys = { path = "../js-sys" }
