[package]
name = "js-sys"
version = "0.0.0"
edition = "2021"
rust-version = "1.59"

[features]
std = []

[build-dependencies]
js-bindgen-shared = { path = "../shared" }

[dependencies]
js-bindgen = { path = "../js-bindgen" }
