[package]
edition = "2021"
name = "js-sys"
rust-version = "1.59"
version = "0.0.0"

[features]
std = []

[build-dependencies]
js-bindgen-bootstrap = { path = "../bootstrap" }

[dependencies]
js-bindgen = { path = "../js-bindgen" }
