[package]
edition = { workspace = true }
license = { workspace = true }
name = "js-bindgen-macro-shared"
rust-version = { workspace = true }

[dependencies]
proc-macro2 = { workspace = true }

[lints]
workspace = true
